apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## TODO Namespace
namespace: dev

#nameSuffix: -v1

resources:
  - ../../base

# Patch Deployment
patchesStrategicMerge:
  - patch-spring-profile.yaml
  - patch-limits.yaml
  - patch-replicas.yaml
  - patch-mongodb-credentials.yaml

# ConfigMap
configMapGenerator:
  - files:
      - config-files/application.yaml
    name: app-config


