apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        # TODO
        - name: kboot-reactive-mongo
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mymongo-mongodb
                  key: mongodb-root-password
