spring:
  profiles:
    active: default
    include: common

  application:
    name: kboot-reactive-mongo

---
spring:
  profiles: local
  data:
    mongodb:
      database: sampledb
      host: localhost
---
spring:
  profiles: development
  data:
    mongodb:
      database: sampledb
      uri: mongodb://root:${MONGODB_PASSWORD}@mymongo-mongodb-0.mymongo-mongodb-headless.dev.svc.cluster.local,mymongo-mongodb-1.mymongo-mongodb-headless.dev.svc.cluster.local
