apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

crds:
  - openshift-route.json

resources:
  - route.yaml

configurations:
  - params.yaml

vars:
  - name: routeName
    objref:
      kind: Route
      name: app
      apiVersion: route.openshift.io/v1
    fieldref:
      fieldpath: metadata.labels.app

  - name: routeNamespace
    objref:
      kind: Route
      name: app
      apiVersion: route.openshift.io/v1
    fieldref:
      fieldpath: metadata.namespace

