apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        # TODO FIXME
        - name: kboot-reactive-mongo
          volumeMounts:
            - mountPath: /config
              name: app-config
      volumes:
        - name: app-config
          configMap:
            name: app-config






